### ISSUE TITLE
E/TwilioPlugin: Couldn't open room. No valid input params  #codova_plugin_android

### ISSUE THREAD

**Issue by Sajanrav01** [okode/cordova-plugin-twilio-video#27]
Hi Team

<img width="1293" alt="Screen Shot 2020-09-17 at 9 37 16 PM" src="https://user-images.githubusercontent.com/2862745/93497390-fe173600-f92d-11ea-90a6-fb5938245f94.png">
 I am getting error  Couldn't open room .No valid input params even if i am passing correct input value in android plugin.

i have validated same plugin in iOS its working fine.but in android its failing.

funcation call - window.twiliovideo.openRoom('token', 'room')
Plugin version  - 4.0.0
Android platform version - cordova-android@9.0.0
Device -Moto G4
NB:Installed AndroidX plugin also

Thanks in Advance. attached error desc image

here is the detailed error desc:

2020-09-17 21:22:26.988 21321-21376/com.example.cordovareactApp E/TwilioPlugin: Couldn't open room. No valid input params
    org.json.JSONException: Value null at 2 of type org.json.JSONObject$1 cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:100)
        at org.json.JSONArray.getJSONObject(JSONArray.java:525)
        at org.apache.cordova.twiliovideo.TwilioVideo.openRoom(TwilioVideo.java:70)
        at org.apache.cordova.twiliovideo.TwilioVideo.execute(TwilioVideo.java:47)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rpanadero** [comment]
@Sajanrav01 , try with this `window.twiliovideo.openRoom('token', 'room', {});`

**Comment by Sajanrav01** [comment]
Thanks!! i will check and update..

**Comment by Sajanrav01** [comment]
Sorry to say, still getting the same error!!

**Comment by rpanadero** [comment]
@Sajanrav01 , sorry for making you do some tests, but I don't have time now to test it. Could you try this?
`window.twiliovideo.openRoom('token', roomName, null, {});`

Anyway, I will fix it in the next release.
